### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by dev-adalz** [largereptile/osutools#3]
**code**

`import osutools
import discord
from discord.ext import commands

osu = osutools.OsuClient("osu_token")
client = commands.Bot(command_prefix="!")

@client.command(name="profile")
async def profile(ctx, *, username):
    user = osu.fetch_user(username=username)
    embed = discord.Embed(title=f"osu! Profile for {user.username}")
    embed.set_thumbnail(url=user.avatar_url)
    embed.add_field(name="Rank", value=f"#{user.rank}")
    embed.add_field(name="pp", value=f"{user.pp}")
    embed.add_field(name="Accuracy", value=f"{round(user.accuracy, 2)}%")
    embed.add_field(name="Playcount", value=f"{user.play_count}")
    await ctx.send(embed=embed)

client.run("My_token")`

**_error_** 
`PS C:\Users\adalz> & python c:/Users/adalz/OneDrive/Documents/GitHub/hello.py
Traceback (most recent call last):
  File "c:/Users/adalz/OneDrive/Documents/GitHub/hello.py", line 1, in <module>
    import osutools
  File "C:\Users\adalz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\osutools\__init__.py", line 1, in <module>
    from .osuclient import OsuClient
  File "C:\Users\adalz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\osutools\osuclient.py", line 3, in <module>
    from .map import Map
  File "C:\Users\adalz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\osutools\map.py", line 5, in <module>
    from .oppai import Oppai
  File "C:\Users\adalz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\osutools\oppai.py", line 11, in <module>
    class Oppai:
  File "C:\Users\adalz\AppData\Local\Programs\Python\Python38-32\lib\site-packages\osutools\oppai.py", line 23, in Oppai
    dll.ezpp_new.restype = c_void_p
  File "C:\Users\adalz\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\adalz\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'ezpp_new' not found`

**Comment by largereptile** [comment]
oh how odd, ill look into it. can you try importing it into a shell as well? uninstalling + reinstalling from pip? it seems like it isnt loading the oppai resource correctly which is uh odd.
